name: Build and Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Extract Version from POM
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Extract Tag Name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Check if Release Already Exists
        id: check_release
        run: |
          EXISTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME" | jq -r '.id')
          if [ "$EXISTS" != "null" ]; then
            echo "Release already exists for tag $TAG_NAME."
            echo "##[error]Release already exists."
            exit 1
          fi

      - name: Create Release
        run: |
          RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "'$TAG_NAME'", "name": "Release '$TAG_NAME'", "draft": false, "prerelease": false}' \
            "https://api.github.com/repos/${{ github.repository }}/releases")
          UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url | sed 's/{?name,label}//')
          if [ -z "$UPLOAD_URL" ] || [ "$UPLOAD_URL" == "null" ]; then
            echo "Failed to create release: $RESPONSE"
            echo "##[error]Failed to create release."
            exit 1
          fi
          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

      - name: Upload JAR to Release
        run: |
          curl -s -X POST "$UPLOAD_URL?name=$(basename ${GITHUB_WORKSPACE}/target/telemetry-nucleus-emitter-${{ env.VERSION }}.jar)" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/java-archive" \
            --data-binary @"${GITHUB_WORKSPACE}/target/telemetry-nucleus-emitter-${{ env.VERSION }}.jar"
