name: Build and Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Extract Version from POM
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Create Release
        run: |
          RELEASE_DATA=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "'${{ github.ref }}'", "name": "Release '${{ github.ref }}'", "draft": false, "prerelease": false}' \
            "https://api.github.com/repos/${{ github.repository }}/releases")
          echo "RELEASE_DATA=$RELEASE_DATA" >> $GITHUB_ENV

      - name: Get Upload URL
        run: echo "UPLOAD_URL=$(echo $RELEASE_DATA | jq -r .upload_url | sed 's/{?name,label}//')" >> $GITHUB_ENV

      - name: Upload JAR to Release
        run: |
          curl -s -X POST "$UPLOAD_URL?name=$(basename ${GITHUB_WORKSPACE}/target/telemetry-nucleus-emitter-${{ env.VERSION }}.jar)" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/java-archive" \
            --data-binary @"${GITHUB_WORKSPACE}/target/telemetry-nucleus-emitter-${{ env.VERSION }}.jar"
